package org.example.docfiller

enum class UserRole{
    ROLE_USER, ROLE_ADMIN
}

enum class ErrorCode(val code: Int, val message: String) {
    //1
    EMPLOYEE_NOT_FOUND(100, "EMPLOYEE_NOT_FOUND"),
    EMPLOYEE_ALREADY_EXISTS(101, "EMPLOYEE_ALREADY_EXISTS"),
    EMPLOYEE_NOT_AUTHENTICATED(102, "EMPLOYEE_NOT_AUTHENTICATED"),
    PHONE_NUMBER_ALREADY_EXISTS(103, "PHONE_NUMBER_ALREADY_EXISTS"),

    INVALID_PASSWORD(103, "INVALID_PASSWORD"),
    // PlaceHolder errors
    ATTACH_NOT_FOUND(200, "ATTACH_NOT_FOUND"),
    PLACEHOLDER_NOT_FOUND(201, "PLACEHOLDER_NOT_FOUND"),
    INVALID_FILE_TYPE(202, "INVALID_FILE_TYPE"),
    FILE_READ_ERROR(203, "FILE_READ_ERROR"),
    //Organization
    ORGANIZATION_ALREADY_EXISTS(300, "ORGANIZATION_ALREADY_EXISTS"),
}

enum class FileType {
    DOCX, PDF
}
